name: update-players-sheet
on:
   schedule:
      - cron: '0 13 * 1-7,11-12 1' # https://crontab.guru
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -  name: checkout repo content
            uses: actions/checkout@v4 # checkout the repository content to github runner
         -  name: setup python
            uses: actions/setup-python@v5
            with:
               python-version: '3.11.2' # install the python version needed
               cache: 'pip' # caching pip dependencies
         -  name: install python packages
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -  name: update players sheet
            env:
               GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
            run: |
               python -c 'import google_sheets; google_sheets.update_canadians_sheet();'
         -  name: email additions
            env:
               GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
            run: |
               python -c 'import scrape; scrape.email_additions("bob");'
         -  name: find player stat ids
            env:
               GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
            run: |
               python -c 'import scrape; scrape.find_player_stat_ids();'
